# Generated by Django 5.1.4 on 2025-01-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('country_code', models.CharField(max_length=5)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
